#!/usr/bin/env bash
set -eo pipefail
scriptDir=$(dirname $0)

java -XX:+UseCompressedOops \
     -XX:MaxJavaStackTraceDepth=10 \
     -cp $scriptDir/akerblad.jar:$scriptDir/lib/scala-library.jar \
     Akerblad $@
